# https://gal.hagever.com/posts/running-vercel-postgres-locally

services:
  postgres:
    image: 'postgres:15.2-alpine'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    ports:
      - '12345:5432'
    volumes:
      - pg-data:/var/lib/postgresql/data
  pg_proxy:
    image: ghcr.io/neondatabase/wsproxy:latest
    restart: always
    environment:
      APPEND_PORT: 'postgres:5432'
      ALLOW_ADDR_REGEX: '.*'
      LOG_TRAFFIC: 'true'
    ports:
      - '23456:80'
    depends_on:
      - postgres

volumes:
  pg-data:
